# Generated by Django 4.0.4 on 2022-05-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='candidates.language', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='candidates.skill', verbose_name='Навык'),
        ),
    ]
